name: ros-example
version: 1.0
summary: ROS Snap Test
description: ROS Snap Test
confinement: strict

apps:
    launch-project:
        command: roslaunch test_pkg run.launch

parts:
    ros-project:
        plugin: catkin
        source: .
        catkin-packages:
            - test_pkg
        include-roscore: true
        rosdistro: kinetic
