// Generated by gencpp from file testmsg/poto.msg
// DO NOT EDIT!


#ifndef TESTMSG_MESSAGE_POTO_H
#define TESTMSG_MESSAGE_POTO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testmsg
{
template <class ContainerAllocator>
struct poto_
{
  typedef poto_<ContainerAllocator> Type;

  poto_()
    : name()
    , id(0)  {
    }
  poto_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int8_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::testmsg::poto_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testmsg::poto_<ContainerAllocator> const> ConstPtr;

}; // struct poto_

typedef ::testmsg::poto_<std::allocator<void> > poto;

typedef boost::shared_ptr< ::testmsg::poto > potoPtr;
typedef boost::shared_ptr< ::testmsg::poto const> potoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testmsg::poto_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testmsg::poto_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'testmsg': ['/home/ahmed/catkin_ws/src/testmsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testmsg::poto_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testmsg::poto_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testmsg::poto_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testmsg::poto_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testmsg::poto_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testmsg::poto_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testmsg::poto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4f347043a64ae4ea786a068b0a9e07c";
  }

  static const char* value(const ::testmsg::poto_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4f347043a64ae4eULL;
  static const uint64_t static_value2 = 0xa786a068b0a9e07cULL;
};

template<class ContainerAllocator>
struct DataType< ::testmsg::poto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testmsg/poto";
  }

  static const char* value(const ::testmsg::poto_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testmsg::poto_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
int8 id\n\
";
  }

  static const char* value(const ::testmsg::poto_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testmsg::poto_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct poto_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testmsg::poto_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testmsg::poto_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTMSG_MESSAGE_POTO_H
